# Generated by Django 6.0.3 on 2026-03-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='prioridad')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha límite')),
                ('position', models.IntegerField(default=0, verbose_name='posición')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completada en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
