# Generated by Django 6.0.3 on 2026-03-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivado')),
                ('background_color', models.CharField(default='#0079BF', help_text='Color hexadecimal', max_length=7, verbose_name='color de fondo')),
            ],
            options={
                'verbose_name': 'tablero',
                'verbose_name_plural': 'tableros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('position', models.IntegerField(default=0, verbose_name='posición')),
                ('color', models.CharField(default='#EBECF0', help_text='Color hexadecimal', max_length=7, verbose_name='color')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivada')),
            ],
            options={
                'verbose_name': 'lista',
                'verbose_name_plural': 'listas',
                'ordering': ['position'],
            },
        ),
    ]
